server:
  port: 8082

logging:
  level:
    # Spring MVC logging
    org.springframework.web: DEBUG
    # Zuul Proxy HTTP logging
    org.apache.http.wire: DEBUG

hello.service:
  url: http://localhost:8081

twitter.service:
  url: https://api.twitter.com/1.1

hystrix:
  command.default:
    # Do not use thread strategy for session scope.
    # http://stackoverflow.com/questions/34677470/spring-feignclient-with-oauth2feignrequestinterceptor-not-working
    execution.isolation.strategy: SEMAPHORE
    execution.isolation.thread.timeoutInMilliseconds: 10000

zuul:
  routes:
    hello:
      path: /api/**
      url: http://localhost:8081

security:
  oauth2:
    twitter:
      access-token-uri: https://api.twitter.com/oauth2/token

authorities:
  hello:
  - x0w9zjiWDrgWWSzNnVCpr9WeIk95d0WZ
  - yee8tfSEOP5lPJOd6akcon1FIFKwwok3
  - 7cgcavhx1CxKCT9IoSqFryx15C5EpWaG
