server:
  port: 8082

logging:
  level:
    # Enable API server logging
    org.springframework.web.filter: DEBUG
    # Enable API client logging
    example.gateway.HelloClient: DEBUG
    # Zuul Proxy HTTP logging
    org.apache.http.wire: DEBUG

hello.service:
  name: hello-service
  url: http://localhost:8081

# https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.thread.timeoutInMilliseconds
hystrix.command.default:
  execution.isolation.thread.timeoutInMilliseconds: 3000

zuul:
  routes:
    hello:
      path: /api/**
      url: http://localhost:8081
