server:
  port: 8082

logging.level:
  example: DEBUG
  # Enable request logging
  org.springframework.web.filter: DEBUG
  # Enable logging of access token request
  org.springframework.web.client: DEBUG
  # Enable request logging
  example.gateway.HelloClient: DEBUG
  # Zuul Proxy HTTP logging
  org.apache.http.wire: DEBUG
  # Web security access control logging
  org.springframework.security.web.access: DEBUG

hello.service:
  url: http://localhost:8081

security:
  basic:
    enabled: false
  oauth2:
    hello:
      access-token-uri: http://localhost:8081/oauth/token
      client-id: theId
      client-secret: theSecret
      scope: theScope

feign.hystrix.enabled: false

zuul:
  routes:
    hello:
      path: /api/**
      url: http://localhost:8081
