logging.level:
  # Enable request logging
  org.springframework.web.filter: DEBUG
  # Web security access control logging
  org.springframework.security.web.access: DEBUG

server:
  port: 8081

security:
  basic:
    enabled: false
  oauth2.client:
    client-id: theId
    client-secret: theSecret
  user:
    name: theUser
    password: thePassword
